@echo off
:: Redefinir conexão do OpenVPN 
:: AUTOR  : Ivo Dias
:: VERSAO : 1.0.MSC

::Desativar o adaptador
wmic path win32_networkadapter where name="TAP-Windows Adapter v9" call disable
cls
echo .......
echo .......
echo Adaptador parado com sucesso
echo .......
echo .......
pause

::Ativar o adpatador
wmic path win32_networkadapter where name="TAP-Windows Adapter v9" call enable
cls
echo .......
echo .......
echo Adaptador ativo com sucesso, assim que o Script encerrar
echo Inicie o OpenVPN Gui
echo .......
echo .......
pause